// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace net6d1.Model
{
    public partial class Cihaz1
    {
        [Key]
        public int Id { get; set; }
        public string AdSoyad { get; set; }
        public string Islem { get; set; }
        public string DetayIslem { get; set; }
        public string Getirilen { get; set; }
        public string Mail { get; set; }
        public string TelNo { get; set; }
        public string Kod { get; set; }
        public DateTime? Vtarih { get; set; }
        public DateTime? Btarih { get; set; }
        public string Durum { get; set; }
        public string Cihaz { get; set; }
    }
}