// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace net6d1.Model
{
    public partial class dContext : DbContext
    {
        public dContext()
        {
        }

        public dContext(DbContextOptions<dContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Cihaz1> Cihaz1s { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Cihaz1>(entity =>
            {
                

                entity.ToView("cihaz1");

                entity.Property(e => e.AdSoyad).HasMaxLength(50);

                entity.Property(e => e.Btarih)
                    .HasColumnType("datetime")
                    .HasColumnName("BTarih");

                entity.Property(e => e.Cihaz).HasColumnType("text");

                entity.Property(e => e.DetayIslem).HasColumnType("text");

                entity.Property(e => e.Durum)
                    .HasMaxLength(50)
                    .HasColumnName("durum");

                entity.Property(e => e.Getirilen).HasColumnType("text");

                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.Islem)
                    .HasMaxLength(50)
                    .HasColumnName("islem");

                entity.Property(e => e.Kod)
                    .HasMaxLength(10)
                    .IsFixedLength();

                entity.Property(e => e.Mail).HasMaxLength(50);

                entity.Property(e => e.TelNo).HasMaxLength(11);

                entity.Property(e => e.Vtarih)
                    .HasColumnType("datetime")
                    .HasColumnName("VTarih");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}